import apple from "../assets/fruits/apple.jpg";
import cherry from "../assets/fruits/cherry.jpg";
import orange from "../assets/fruits/orange.jpg";
import pineapple from "../assets/fruits/pineapple.jpg";
import strawberry from "../assets/fruits/strawberry.jpg";
import watermelon from "../assets/fruits/watermelon.jpg";
import broccoli from "../assets/vegetable/broccoli.jpg";
import carrot from "../assets/vegetable/carrot.png";
import cauliflower from "../assets/vegetable/cauli.jpg";
import tomato from "../assets/vegetable/tomato.jpg";
import spinach from "../assets/vegetable/spinach.jpg";
import cheese from "../assets/dairy/cheese.jpg";
import curd from "../assets/dairy/curd.jpg";
import milk from "../assets/dairy/milk.jpg";
import yogurt from "../assets/dairy/yogurt.jpg";
import icecream from "../assets/dairy/icecream.jpg";
import coffemate from "../assets/dairy/coffemate.jpg";
import rice from "../assets/treat/rice.jpg";
import choci from "../assets/treat/choci.jpg";
import lolli from "../assets/treat/lolli.jpg";
import bourbon from "../assets/treat/bourbon.jpg";





const items = [
  {
    id: "db1",
    name: "Apple",
    price: 9.99,
    manufacturer: "Remo",
    discount: 15,
    // accessories: ["a1", "a2", "a3", "a4"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    image: apple,
    category: 1,
  },
  {
    id: "db2",
    name: "Cherry",
    price: 5.99,
    manufacturer: "Remo",
    discount: 10,
    // accessories: ["a1", "a2", "a3", "a4"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    image: cherry,
    category: 1,
  },
  {
    id: "db3",
    name: "Orange",
    price: 4.99,
    manufacturer: "Blink",
    discount: 50,
    // accessories: ["a5", "a6"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    image: orange,
    category: 1,
  },
  {
    id: "db4",
    name: "Pineapple",
    price: 300.99,
    manufacturer: "Blink",
    discount: 25,
    // accessories: ["a5", "a6"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    image: pineapple,
    category: 1,
  },
  {
    id: "db5",
    name: "Strawberry",
    price: 3.99,
    manufacturer: "Ring",
    discount: 30,
    // accessories: ["a7", "a8"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    image: strawberry,
    category: 1,
  },
  {
    id: "db6",
    name: "Watermelon",
    price: 2.99,
    manufacturer: "Ring",
    discount: 15,
    // accessories: ["a7", "a8"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    image: watermelon,
    category: 1,
  },
  {
    id: "dl1",
    name: "Broccoli",
    price: 9.99,
    manufacturer: "Remo",
    discount: 15,
    // accessories: ["a1", "a2", "a3", "a4"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    image: broccoli,
    category: 2,
  },
  {
    id: "dl2",
    name: "Carrot",
    price: 5.99,
    manufacturer: "Remo",
    discount: 10,
    image: carrot,
    // accessories: ["a1", "a2", "a3", "a4"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    category: 2,
  },
  {
    id: "dl3",
    name: "Caulliflower",
    price: 4.99,
    manufacturer: "Blink",
    discount: 50,
    image: cauliflower,
    // accessories: ["a5", "a6"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    category: 2,
  },
  {
    id: "dl4",
    name: "Tomato",
    price: 3.99,
    manufacturer: "Blink",
    discount: 25,
    image: tomato,
    // accessories: ["a5", "a6"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    category: 2,
  },
  {
    id: "dl5",
    name: "Spinach",
    price: 3.99,
    manufacturer: "Ring",
    discount: 30,
    image: spinach,
    // accessories: ["a7", "a8"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    category: 2,
  },
  {
    id: "s1",
    name: "Cheese",
    price: 9.99,
    manufacturer: "Amazon",
    discount: 15,
    image: cheese,
    // accessories: ["a1", "a2", "a3", "a4"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    category: 3,
  },
  {
    id: "s2",
    name: "Curd",
    price: 5.99,
    manufacturer: "Amazon",
    discount: 10,
    image: curd,
    // accessories: ["a1", "a2", "a3", "a4"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    category: 3,
  },
  {
    id: "s3",
    name: "Milk",
    price: 4.99,
    manufacturer: "Google",
    discount: 50,
    image: milk,
    // accessories: ["a5", "a6"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    category: 3,
  },
  {
    id: "s4",
    name: "Yogurt",
    price: 0.99,
    manufacturer: "Google",
    discount: 25,
    image: yogurt,
    // accessories: ["a5", "a6"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    category: 3,
  },
  {
    id: "s5",
    name: "Ice Cream",
    price: 349.99,
    manufacturer: "Google",
    discount: 30,
    image: icecream,
    // accessories: ["a7", "a8"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    category: 3,
  },
  {
    id: "s6",
    name: "Coffee Mate",
    price: 299.99,
    manufacturer: "Apple",
    discount: 15,
    image: coffemate,
    // accessories: ["a7", "a8"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    category: 3,
  },
  {
    id: "l1",
    name: "Rice Cake",
    price: 9.99,
    manufacturer: "Philips",
    discount: 15,
    image: rice,
    // accessories: ["a1", "a2", "a3", "a4"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    category: 4,
  },
  {
    id: "l2",
    name: "Choci",
    price: 5.99,
    manufacturer: "Philips",
    discount: 10,
    image: choci,
    // accessories: ["a1", "a2", "a3", "a4"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    category: 4,
  },
  {
    id: "l3",
    name: "Lollipop",
    price: 449.99,
    manufacturer: "Philips",
    discount: 50,
    image: lolli,
    // accessories: ["a5", "a6"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    category: 4,
  },
  {
    id: "l4",
    name: "Bourbon",
    price: 3.99,
    manufacturer: "Philips",
    discount: 25,
    image: bourbon,
    // accessories: ["a5", "a6"],
    available : 1,
    onSale : 1,
    manufacturerRebate : 1,
    category: 4,
  },
];

const categories = [
  {
    id: 1,
    label: "Fruits",
    title: "Fresh Fruits",
  },
  {
    id: 2,
    label: "Vegetables",
    title: "Fresh Vegetables",
  },
  {
    id: 3,
    label: "Dairy",
    title: "Fresh Dairy",
  },
  {
    id: 4,
    label: "Treats",
    title: "Sweet Treats",
  }
];

const userTypes = {
  CUSTOMER: "customer",
  STORE_MANAGER: "storemanager",
  SALES_MANAGER: "salesmanager",
};

export { categories, userTypes, items };
